# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(verbose_name=b'%d/%m/%Y %H:%M:%S')),
                ('updated_at', models.DateTimeField(verbose_name=b'%m/%d/%Y %H:%M:%S')),
            ],
        ),
    ]
