# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('search', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('telephone', models.BooleanField(max_length=20)),
                ('password', models.BooleanField(max_length=20)),
                ('number', models.BooleanField(max_length=15)),
                ('created_at', models.DateTimeField(verbose_name=b'%m/%d/%Y %H:%M:%S')),
                ('updated_at', models.DateTimeField(verbose_name=b'%m/%d/%Y %H:%M:%S')),
            ],
        ),
    ]
