# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_ajax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajax',
            name='number',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ajax',
            name='password',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ajax',
            name='telephone',
            field=models.IntegerField(max_length=20),
        ),
    ]
