# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20171104_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajax',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
