# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20171104_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajax',
            name='firstname',
            field=models.CharField(default='111', max_length=40),
            preserve_default=False,
        ),
    ]
