# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_ajax_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajax',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='ajax',
            name='lastname',
        ),
    ]
